name: sync2gitee
on:
  workflow_run:
    workflows: [Excavator]
    types:
      - completed
  #schedule:
  #  - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/GeorgeDong32
          dst: gitee/GeorgeDong32
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "scoopgd"
