# This is a basic workflow to help you get started with Actions

name: sync2gitee

# Controls when the workflow will run
on:
  schedule:
    # every Friday
    - cron: '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Black list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/GeorgeDong32
          dst: gitee/GeorgeDong32
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "scoopgd"
